require 'slack-mathbot/commands/base'
require 'slack-mathbot/commands/calculate'
require 'slack-mathbot/commands/about'
require 'slack-mathbot/commands/help'
require 'slack-mathbot/commands/hi'
require 'slack-mathbot/commands/unknown'
